apiVersion: v1
kind: Secret
metadata:
  name: {{ if .Values.secretName }}{{ .Values.secretName }}{{ else }}{{ include "fastapi-app.fullname" . }}{{ end }}
type: Opaque
data:
  api_key: {{ randAlphaNum 32 | b64enc }}